name=WaveShare P4 Smart86 Drivers
version=0.0.1
author=Marge
maintainer=Marge
sentence=Init commands and configuration for WaveShare P4 Smart86 MIPI DSI display.
paragraph=This library provides initialization commands and configuration settings for the WaveShare P4 Smart86 MIPI DSI display, enabling seamless integration with Arduino GFX Library.
url=
