// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_top_bar;
extern lv_obj_t * ui_Label1;
extern void ui_event_ponel_touch_data(lv_event_t * e);
extern lv_obj_t * ui_ponel_touch_data;
extern lv_obj_t * ui_label_header;
extern lv_obj_t * ui_label_count;
extern lv_obj_t * ui_bottom_deck;
extern lv_obj_t * ui_Panel_Audio;
extern lv_obj_t * ui_row1_title;
extern lv_obj_t * ui_label__audio_title;
extern lv_obj_t * ui_row2_volume_label_and_slider;
extern lv_obj_t * ui_amp_and_switch;
extern lv_obj_t * ui_enable;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_vol_slider__and_label;
extern lv_obj_t * ui_VOLUME;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_buttons;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel_Display;
extern lv_obj_t * ui_ROW_vol_slider_and_label;
extern lv_obj_t * ui_Brightness;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_ROW_touches;
extern lv_obj_t * ui_Show_touches;
extern lv_obj_t * ui_SWITCH_touches;
// CUSTOM VARIABLES
extern lv_obj_t * uic_panel_touch_data;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

