// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_panel_touch_data;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_top_bar = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ponel_touch_data = NULL;
lv_obj_t * ui_label_header = NULL;
lv_obj_t * ui_label_count = NULL;
lv_obj_t * ui_bottom_deck = NULL;
lv_obj_t * ui_Panel_Audio = NULL;
lv_obj_t * ui_row1_title = NULL;
lv_obj_t * ui_label__audio_title = NULL;
lv_obj_t * ui_row2_volume_label_and_slider = NULL;
lv_obj_t * ui_amp_and_switch = NULL;
lv_obj_t * ui_enable = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_vol_slider__and_label = NULL;
lv_obj_t * ui_VOLUME = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_buttons = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel_Display = NULL;
lv_obj_t * ui_ROW_vol_slider_and_label = NULL;
lv_obj_t * ui_Brightness = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_ROW_touches = NULL;
lv_obj_t * ui_Show_touches = NULL;
lv_obj_t * ui_SWITCH_touches = NULL;
// event funtions
void ui_event_ponel_touch_data(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        drag_event_handler(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_top_bar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_top_bar);
    lv_obj_set_height(ui_top_bar, 50);
    lv_obj_set_width(ui_top_bar, lv_pct(100));
    lv_obj_set_align(ui_top_bar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_top_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_top_bar, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_top_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_top_bar, lv_color_hex(0x00A8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_top_bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_top_bar, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_top_bar, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_top_bar);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "Waveshare P4 7\" Touch-LCD-7B");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x00A8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ponel_touch_data = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ponel_touch_data);
    lv_obj_set_width(ui_ponel_touch_data, 180);
    lv_obj_set_height(ui_ponel_touch_data, 210);
    lv_obj_set_x(ui_ponel_touch_data, -10);
    lv_obj_set_y(ui_ponel_touch_data, -50);
    lv_obj_set_align(ui_ponel_touch_data, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_ponel_touch_data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ponel_touch_data, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ponel_touch_data, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ponel_touch_data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ponel_touch_data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ponel_touch_data, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ponel_touch_data, lv_color_hex(0x00A8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ponel_touch_data, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ponel_touch_data, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ponel_touch_data, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_header = lv_label_create(ui_ponel_touch_data);
    lv_obj_set_width(ui_label_header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_header, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_header, "TOUCH POINTS");
    lv_obj_set_style_text_color(ui_label_header, lv_color_hex(0x00A8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_label_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_label_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_label_header, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_label_header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_count = lv_label_create(ui_ponel_touch_data);
    lv_obj_set_width(ui_label_count, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_count, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_count, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_label_count, "ACTIVE: 0");
    lv_obj_set_style_text_color(ui_label_count, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_count, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_count, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bottom_deck = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_bottom_deck);
    lv_obj_set_height(ui_bottom_deck, 160);
    lv_obj_set_width(ui_bottom_deck, lv_pct(100));
    lv_obj_set_align(ui_bottom_deck, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_bottom_deck, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_bottom_deck, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_bottom_deck, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_bottom_deck, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_bottom_deck, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_bottom_deck, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_bottom_deck, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_bottom_deck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_bottom_deck, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel_Audio = lv_obj_create(ui_bottom_deck);
    lv_obj_set_height(ui_Panel_Audio, lv_pct(100));
    lv_obj_set_flex_grow(ui_Panel_Audio, 1);
    lv_obj_set_align(ui_Panel_Audio, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel_Audio, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel_Audio, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel_Audio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel_Audio, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Audio, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Audio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Audio, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Audio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Audio, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Audio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Audio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Audio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Audio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel_Audio, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel_Audio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row1_title = lv_obj_create(ui_Panel_Audio);
    lv_obj_remove_style_all(ui_row1_title);
    lv_obj_set_width(ui_row1_title, lv_pct(100));
    lv_obj_set_height(ui_row1_title, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_row1_title, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_row1_title, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_row1_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_row1_title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_row1_title, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label__audio_title = lv_label_create(ui_row1_title);
    lv_obj_set_width(ui_label__audio_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label__audio_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label__audio_title, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label__audio_title, "AUDIO");
    lv_obj_set_style_text_color(ui_label__audio_title, lv_color_hex(0x00A8FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label__audio_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_row2_volume_label_and_slider = lv_obj_create(ui_Panel_Audio);
    lv_obj_remove_style_all(ui_row2_volume_label_and_slider);
    lv_obj_set_height(ui_row2_volume_label_and_slider, 45);
    lv_obj_set_width(ui_row2_volume_label_and_slider, lv_pct(100));
    lv_obj_set_align(ui_row2_volume_label_and_slider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_row2_volume_label_and_slider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_row2_volume_label_and_slider, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_row2_volume_label_and_slider, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_row2_volume_label_and_slider, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_row2_volume_label_and_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_row2_volume_label_and_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_row2_volume_label_and_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_row2_volume_label_and_slider, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_amp_and_switch = lv_obj_create(ui_row2_volume_label_and_slider);
    lv_obj_remove_style_all(ui_amp_and_switch);
    lv_obj_set_width(ui_amp_and_switch, 65);
    lv_obj_set_height(ui_amp_and_switch, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_amp_and_switch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_amp_and_switch, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_amp_and_switch, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_amp_and_switch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_amp_and_switch, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_amp_and_switch, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_amp_and_switch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_amp_and_switch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_amp_and_switch, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_amp_and_switch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_enable = lv_label_create(ui_amp_and_switch);
    lv_obj_set_width(ui_enable, lv_pct(100));
    lv_obj_set_height(ui_enable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_enable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_enable, "ENABLE");
    lv_obj_set_style_text_color(ui_enable, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_enable, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_enable, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_enable, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_amp_and_switch);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_width(ui_Switch2, lv_pct(100));
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch2, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_min_height(ui_Switch2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Switch2, 8192, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vol_slider__and_label = lv_obj_create(ui_row2_volume_label_and_slider);
    lv_obj_remove_style_all(ui_vol_slider__and_label);
    lv_obj_set_height(ui_vol_slider__and_label, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_flex_grow(ui_vol_slider__and_label, 1);
    lv_obj_set_align(ui_vol_slider__and_label, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_vol_slider__and_label, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_vol_slider__and_label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_vol_slider__and_label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_vol_slider__and_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider__and_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_vol_slider__and_label, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_vol_slider__and_label, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_vol_slider__and_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_vol_slider__and_label, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_vol_slider__and_label, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_vol_slider__and_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VOLUME = lv_label_create(ui_vol_slider__and_label);
    lv_obj_set_width(ui_VOLUME, lv_pct(100));
    lv_obj_set_height(ui_VOLUME, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VOLUME, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOLUME, "VOLUME");
    lv_obj_set_style_text_color(ui_VOLUME, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VOLUME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_VOLUME, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VOLUME, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_vol_slider__and_label);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, lv_pct(100));
    lv_obj_set_flex_grow(ui_Slider1, 1);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_min_height(ui_Slider1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Slider1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_buttons = lv_obj_create(ui_Panel_Audio);
    lv_obj_remove_style_all(ui_buttons);
    lv_obj_set_height(ui_buttons, 45);
    lv_obj_set_width(ui_buttons, lv_pct(100));
    lv_obj_set_align(ui_buttons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_buttons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_buttons, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_buttons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_pad_row(ui_buttons, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_buttons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_buttons);
    lv_obj_set_height(ui_Button2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_flex_grow(ui_Button2, 1);
    lv_obj_set_x(ui_Button2, 169);
    lv_obj_set_y(ui_Button2, -5);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_min_width(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_Button2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Label2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Label2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(ui_Label2, "TONE");

    ui_Button3 = lv_button_create(ui_buttons);
    lv_obj_set_height(ui_Button3, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_flex_grow(ui_Button3, 1);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_min_width(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_Button3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PCM");

    ui_Panel_Display = lv_obj_create(ui_bottom_deck);
    lv_obj_set_height(ui_Panel_Display, lv_pct(100));
    lv_obj_set_flex_grow(ui_Panel_Display, 1);
    lv_obj_set_align(ui_Panel_Display, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel_Display, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Panel_Display, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel_Display, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel_Display, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel_Display, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Display, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Display, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Display, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel_Display, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Display, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Display, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Display, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Display, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel_Display, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel_Display, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ROW_vol_slider_and_label = lv_obj_create(ui_Panel_Display);
    lv_obj_remove_style_all(ui_ROW_vol_slider_and_label);
    lv_obj_set_width(ui_ROW_vol_slider_and_label, lv_pct(100));
    lv_obj_set_height(ui_ROW_vol_slider_and_label, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_ROW_vol_slider_and_label, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_flex_flow(ui_ROW_vol_slider_and_label, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ROW_vol_slider_and_label, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_ROW_vol_slider_and_label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ROW_vol_slider_and_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ROW_vol_slider_and_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ROW_vol_slider_and_label, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ROW_vol_slider_and_label, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ROW_vol_slider_and_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ROW_vol_slider_and_label, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ROW_vol_slider_and_label, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ROW_vol_slider_and_label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Brightness = lv_label_create(ui_ROW_vol_slider_and_label);
    lv_obj_set_width(ui_Brightness, lv_pct(100));
    lv_obj_set_height(ui_Brightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Brightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Brightness, "BRIGHTNESS");
    lv_obj_set_style_text_color(ui_Brightness, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Brightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Brightness, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Brightness, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_ROW_vol_slider_and_label);
    lv_slider_set_range(ui_Slider2, 43, 100);
    lv_slider_set_value(ui_Slider2, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, lv_pct(100));
    lv_obj_set_flex_grow(ui_Slider2, 1);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Slider2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_min_height(ui_Slider2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_height(ui_Slider2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider2,
                                                                                              lv_obj_get_style_pad_right(ui_Slider2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_ROW_touches = lv_obj_create(ui_Panel_Display);
    lv_obj_remove_style_all(ui_ROW_touches);
    lv_obj_set_height(ui_ROW_touches, 45);
    lv_obj_set_width(ui_ROW_touches, lv_pct(100));
    lv_obj_set_align(ui_ROW_touches, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ROW_touches, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ROW_touches, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ROW_touches, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_ROW_touches, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ROW_touches, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ROW_touches, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ROW_touches, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ROW_touches, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ROW_touches, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Show_touches = lv_label_create(ui_ROW_touches);
    lv_obj_set_width(ui_Show_touches, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Show_touches, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Show_touches, 67);
    lv_obj_set_y(ui_Show_touches, 170);
    lv_obj_set_align(ui_Show_touches, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Show_touches, "Show Touches");
    lv_obj_set_style_text_color(ui_Show_touches, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Show_touches, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Show_touches, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Show_touches, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SWITCH_touches = lv_switch_create(ui_ROW_touches);
    lv_obj_set_height(ui_SWITCH_touches, 25);
    lv_obj_set_flex_grow(ui_SWITCH_touches, 1);
    lv_obj_set_align(ui_SWITCH_touches, LV_ALIGN_CENTER);
    lv_obj_set_style_min_width(ui_SWITCH_touches, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_SWITCH_touches, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ponel_touch_data, ui_event_ponel_touch_data, LV_EVENT_ALL, NULL);
    uic_panel_touch_data = ui_ponel_touch_data;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_top_bar = NULL;
    ui_Label1 = NULL;
    uic_panel_touch_data = NULL;
    ui_ponel_touch_data = NULL;
    ui_label_header = NULL;
    ui_label_count = NULL;
    ui_bottom_deck = NULL;
    ui_Panel_Audio = NULL;
    ui_row1_title = NULL;
    ui_label__audio_title = NULL;
    ui_row2_volume_label_and_slider = NULL;
    ui_amp_and_switch = NULL;
    ui_enable = NULL;
    ui_Switch2 = NULL;
    ui_vol_slider__and_label = NULL;
    ui_VOLUME = NULL;
    ui_Slider1 = NULL;
    ui_buttons = NULL;
    ui_Button2 = NULL;
    ui_Label2 = NULL;
    ui_Button3 = NULL;
    ui_Label3 = NULL;
    ui_Panel_Display = NULL;
    ui_ROW_vol_slider_and_label = NULL;
    ui_Brightness = NULL;
    ui_Slider2 = NULL;
    ui_ROW_touches = NULL;
    ui_Show_touches = NULL;
    ui_SWITCH_touches = NULL;

}
