name=Board Support Package
version=0.0.1
author=Marge
maintainer=Marge
sentence=Pinouts and initialization commands for touch displays used in my ESP32-based projects.
paragraph=This library provides pinout definitions and initialization commands for various touch displays, ensuring compatibility and ease of use in my ESP32-based projects.
url=
