name=TouchManager
version=0.2.0
author=Marge
maintainer=Marge
sentence=Init commands and configuration for touch displays.
paragraph=This library provides initialization commands and configuration settings for touch displays, enabling seamless integration with Arduino GFX Library.
url=
