name=AudioManager
version=0.0.1
author=Marge
maintainer=Marge
sentence=Init commands and configuration for I2S codec management.
paragraph=This library provides initialization commands and configuration settings for audio management, enabling seamless integration with Arduino GFX Library.
url=
