; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = waveshare_s3_smart86_ex00_hello_arduinogfx
extra_configs = platformio_override.ini
build_cache_dir = .pio/build_cache

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[common]
lib_extra_dirs = /components
lib_deps = 
build_flags = 
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -mfix-esp32-psram-cache-issue
    -I components/lvgl
    -I include/lvgl
    ;-D LV_CONF_INCLUDE_SIMPLE


[env:guition_3_5_base]
board = esp32-s3-n16r8-Guition_JC3248W535EN
lib_extra_dirs = /components
lib_deps = 
    GFX_Library_for_Arduino=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/GFX_Library_for_Arduino
    bb_captouch_fork=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/bb_captouch_fork
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_IDF_TARGET_ESP32S3
    -mfix-esp32-psram-cache-issue
    -I components/lvgl
    -I include/lvgl
    -D GUITION_3248W535
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio


[env:waveshare_s3_smart86_base]
board = esp32-s3-devkitc1-n16r8     ;board = esp32-s3-devkitc-1
lib_extra_dirs = /components
lib_deps = 
    lewisxhe/SensorLib @ ^0.3.3
    lewisxhe/XPowersLib @ ^0.3.1
    GFX Library for Arduino@1.6.0     ;#1.6.0-Waveshare
    ;https://github.com/psyfiend/Arduino_GFX.git#1.6.0-Waveshare  ;Vendor specific version for Waveshare S3 SMART86

build_flags = 
    ${common.build_flags}
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_IDF_TARGET_ESP32S3
    -mfix-esp32-psram-cache-issue
    -I components/lvgl
    -I include/lvgl
    -D WS_S3_SMART86
    -D RGB_PANEL
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv