[env:guition_3_5_ex03_hello_arduino_gfx]
extends = env:guition_3_5_base
lib_deps = 
    ${env:guition_3_5_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
    
build_flags = 
    ${env:guition_3_5_base.build_flags}
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/main_refactored_DisplayManager_test.cpp> ; Refactored DisplayManager test with Arduino_GFX
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/02_GFX_AsciiTable.cpp> ; GFX Ascii Table test
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/HelloWorld.cpp> ; Basic Hello World test
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/HelloWorld_DisplayManager.cpp> ; Basic Hello World test with DisplayManager
build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/LVGL_captouch.cpp> ; LVGL Captouch test



[env:waveshare_s3_smart86_ex01_hello_lvgl]
extends = env:waveshare_s3_smart86_base
;build_flags = ${waveshare_s3_smart86_base.build_flags}
lib_deps = 
    ${env:waveshare_s3_smart86_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
    
;build_src_filter = +<../src/WS_S3_SMART86/ex01_Hello_LVGL/03_LVGL_PCF85063_simpleTime.cpp> ; LVGL with PCF85063 RTC simple time display
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/04_LVGL_QMI8658_ui.cpp> ; LVGL with QMI8658 IMU based UI navigation
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/05_LVGL_AXP2101_ADC_Data.cpp> ; LVGL with AXP2101 power management ADC data display
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/AXP2101 Charge Monitor/*> ; AXP2101 power management charge monitor UI
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/gemini_LVGL_hello_world.cpp> ; Basic LVGL Hello World test
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/hello_display_init.cpp> ; Display init with LVGL log output
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/main_refactored_DisplayManager_test.cpp> ; Refactored DisplayManager test with LVGL
build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/LVGL_captouch.cpp> ; LVGL Captouch test


[env:guition_8048w550_ex01_hello_arduino_gfx]
extends = env:guition_8048w550_base
lib_deps = 
    ${env:guition_8048w550_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/guition_8048/ex01_Hello_Arduino_GFX/HelloWorld_DisplayManager.cpp> ; Basic Hello World test with DisplayManager   
;build_src_filter = +<../src/guition_8048/ex01_Hello_Arduino_GFX/main_refactored_DisplayManager_test.cpp> ; Refactored DisplayManager test with Arduino_GFX
;build_src_filter = +<../src/guition_8048/ex01_hello_arduino_gfx/LVGL_captouch.cpp> ; LVGL Captouch test
;build_src_filter = +<../src/guition_8048/ex01_Hello_Arduino_GFX/02_GFX_AsciiTable.cpp> ; GFX Ascii Table test

[env:guition_8048w550_ex02_hello_lvgl]
extends = env:guition_8048w550_base
lib_deps = 
    ${env:guition_8048w550_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/guition_8048/ex02_Hello_LVGL/LVGL_captouch.cpp> ; LVGL Captouch test

[env:waveshare_p4_smart86_ex00_getting_started]
extends = env:waveshare_p4_smart86_base