; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = guition_3_5_ex03_hello_arduino_gfx
extra_configs = platformio_override.ini
build_cache_dir = .pio/build_cache
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
[common]
lib_extra_dirs = /components
lib_dir = /components
;lib_ldf_mode = deep+
lib_deps = 
    GFX_Library_for_Arduino =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/GFX_Library_for_Arduino
    bb_captouch_fork        =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/bb_captouch_fork
    DisplayManager          =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/DisplayManager
    TouchManager            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/TouchManager
    AudioManager            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/AudioManager
    Fleet_BSP               =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/Fleet_BSP

[S3-options]
build_flags = 
    -D CONFIG_IDF_TARGET_ESP32S3
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D ARDUINO_USB_MODE=1
    -mfix-esp32-psram-cache-issue
    -I components/lvgl
    -I include/lvgl
[P4-options]
build_flags = 
    -D CONFIG_IDF_TARGET_ESP32P4
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC=1
    -D ARDUINO_USB_MODE=1
    -D CONFIG_SPIRAM=1
    -D DOUBLE_BUFFER=1
    -I components/lvgl
    -I include/lvgl



[env:guition_3_5_base]
board = esp32-s3-n16r8-Guition_JC3248W535EN
lib_extra_dirs = /components
lib_deps = 
    ${common.lib_deps}
    lvgl            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
build_flags = 
    ${S3-options.build_flags}
    -D BSP_HEADER='"BSP_CYD_S3_3248W535.h"'
    -D GUITION_3248W535
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
build_src_filter = +<../src/_Common/*> ; Common LVGL Test UI elements

[env:guition_8048w550_base]
board = esp32-s3-devkitc1-n16r8
lib_extra_dirs = /components
lib_deps = 
    ${common.lib_deps}
    lvgl            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
build_flags = 
    ${S3-options.build_flags}
    -D BSP_HEADER='"BSP_CYD_S3_8048W550.h"'
    -D GUITION_8048W550
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
build_src_filter = +<../src/_Common/*> ; Common LVGL Test UI elements

[env:guition_1060p470c_base]
board = esp32-p4-evboard
lib_extra_dirs = /components
lib_deps = ${common.lib_deps}
    lvgl            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
build_flags =
    ${P4-options.build_flags}
    -D BSP_HEADER='"BSP_CYD_P4_1060P470.h"'
    -D GUITION_1060P470
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_upload.flash_size = 16MB
build_src_filter = +<../src/_Common/*> ; Common LVGL Test UI elements


[env:waveshare_s3_smart86_base]
board = esp32-s3-devkitc1-n16r8
lib_extra_dirs = /components
lib_deps = 
    ${common.lib_deps}
    lvgl            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
    lewisxhe/SensorLib @ ^0.3.3
    lewisxhe/XPowersLib @ ^0.3.1
build_flags = 
    ${S3-options.build_flags}
    -D BSP_HEADER='"BSP_WS_S3_Smart86.h"'
    -D DOUBLE_BUFFER
    -D WS_S3_SMART86
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_upload.flash_size = 16MB
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
build_src_filter = +<../src/_Common/*> ; Common LVGL Test UI elements


[env:waveshare_p4_smart86_base]
board = esp32-p4-evboard
lib_extra_dirs = /components
lib_deps = 
    ${common.lib_deps}
    lvgl            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
build_flags =
    ${P4-options.build_flags}
    -D BSP_HEADER='"BSP_WS_P4_Smart86.h"'
    -D WS_P4_SMART86
board_build.partitions = default_16MB.csv
build_src_filter = +<../src/_Common/*> ; Common LVGL Test UI elements


[env:waveshare_p4_7b_base]
board = esp32-p4-evboard
;lib_ldf_mode = deep+
lib_extra_dirs = /components
lib_deps = 
    ${common.lib_deps}
    lvgl            =symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
build_flags =
    ${P4-options.build_flags}
    -D BSP_HEADER='"BSP_WS_P4_7B.h"'
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = default_16MB.csv
build_src_filter = +<../src/_Common/*> ; Common LVGL Test UI elements

