; PlatformIO Override Configuration
;
; This file contains all the specific test environments
; for our "Master Test Harness".
;
; Each environment here extends a "base" definition
; from platformio.ini

[env:guition_3_5_ex00_hello_bb_spi]
extends = env:guition_3_5_base
lib_deps = 
    ${env:guition_3_5_base.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
build_flags = ${env:guition_3_5_base.build_flags}
; build_src_filter = +<../src/guition_3_5/ex00_hello_bb_spi/main_00_00.cpp> ; fillScreen() test
build_src_filter = +<../src/guition_3_5/ex00_hello_bb_spi/main_00_01.cpp> ; Primitive tests: drawing, shapes, text, fills etc


[env:guition_3_5_ex01_hello_bb_captouch]
extends = env:guition_3_5_base
lib_deps = 
    ${env:guition_3_5_base.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
build_flags =  ${env:guition_3_5_base.build_flags}
build_src_filter = +<../src/guition_3_5/ex01_hello_bb_captouch/main_01_01.cpp> ; Basic verification of BB CapTouch
;build_src_filter = +<../src/guition_3_5/ex01_hello_bb_captouch/main_01_02.cpp> ; Rotation testing with touch || 90 & 270 not functional
;build_src_filter = +<../src/guition_3_5/ex01_hello_bb_captouch/main_01_03.cpp> ; Weird test that gemini spontanesouly generated


[env:guition_3_5_ex02_hello_lvgl]
extends = env:guition_3_5_base
lib_deps = 
    ${env:guition_3_5_base.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
    lvgl/lvgl @ ^9.3.0
build_flags = 
    ${env:guition_3_5_base.build_flags}
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_SKIP
build_src_filter = +<../src/guition_3_5/ex02_hello_lvgl/main_02_01.cpp>


[env:guition_3_5_ex03_hello_arduino_gfx]
extends = env:guition_3_5_base
lib_deps = 
    ${env:guition_3_5_base.lib_deps}
    lvgl_common=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl_common
    
build_flags = 
    ${env:guition_3_5_base.build_flags}
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/main_refactored_DisplayManager_test.cpp> ; Refactored DisplayManager test with Arduino_GFX
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/02_GFX_AsciiTable.cpp> ; GFX Ascii Table test
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/HelloWorld.cpp> ; Basic Hello World test
;build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/HelloWorld_DisplayManager.cpp> ; Basic Hello World test with DisplayManager
build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/LVGL_captouch.cpp


[env:waveshare_s3_smart86_base]
extends = env:waveshare_s3_smart86_base
lib_deps = 
    ${env:waveshare_s3_smart86_base.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
build_src_filter = +<../src/WS_S3_SMART86/ex00_hello_bb_spi/main_00_00.cpp> ; fillScreen() test
;build_src_filter = +<../src/WS_S3_SMART86/ex00_hello_bb_spi/main_00_01.cpp> ; Primitive tests: drawing, shapes, text, fills etc


[env:waveshare_s3_smart86_ex00_hello_arduinogfx]
extends = env:waveshare_s3_smart86_base
build_src_filter = +<../src/WS_S3_SMART86/ex000_Hello_Arduino_GFX/01_HelloWorld.cpp> ; Basic Hello World test
;build_src_filter = +<../src/WS_S3_SMART86/ex000_Hello_Arduino_GFX/main_000_01.cpp> ; Basic fillScreen() test
;build_src_filter = +<../src/WS_S3_SMART86/ex000_Hello_Arduino_GFX/PDQGraphicsTest.cpp> ; PDQGraphicsTest
;build_src_filter = +<../src/WS_S3_SMART86/ex000_Hello_Arduino_GFX/02_GFX_AsciiTable.cpp> ; GFX Ascii Table test


[env:waveshare_s3_smart86_ex01_hello_lvgl]
extends = env:waveshare_s3_smart86_base
;build_flags = ${waveshare_s3_smart86_base.build_flags}
lib_deps = 
    ${env:waveshare_s3_smart86_base.lib_deps}
    lvgl_common=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl_common
    
;build_src_filter = +<../src/WS_S3_SMART86/ex01_Hello_LVGL/03_LVGL_PCF85063_simpleTime.cpp> ; LVGL with PCF85063 RTC simple time display
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/04_LVGL_QMI8658_ui.cpp> ; LVGL with QMI8658 IMU based UI navigation
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/05_LVGL_AXP2101_ADC_Data.cpp> ; LVGL with AXP2101 power management ADC data display
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/AXP2101 Charge Monitor/*> ; AXP2101 power management charge monitor UI
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/gemini_LVGL_hello_world.cpp> ; Basic LVGL Hello World test
;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/hello_display_init.cpp> ; Display init with LVGL log output
build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/main_refactored_DisplayManager_test.cpp> ; Refactored DisplayManager test with LVGL