; PlatformIO Override Configuration
;
; This file contains all the specific test environments
; for our "Master Test Harness".
;
; Each environment here extends a "base" definition
; from platformio.ini

[env:guition_3_5_ex00_hello_bb_spi]
extends = env:guition_3_5_base
lib_deps = 
    ${common.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
build_flags = ${common.build_flags}
; build_src_filter = +<../src/guition_3_5/ex00_hello_bb_spi/main_00_00.cpp> ; fillScreen() test
build_src_filter = +<../src/guition_3_5/ex00_hello_bb_spi/main_00_01.cpp> ; Primitive tests: drawing, shapes, text, fills etc


[env:guition_3_5_ex01_hello_bb_captouch]
extends = env:guition_3_5_base
lib_deps = 
    ${common.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
build_flags =  ${common.build_flags}
build_src_filter = +<../src/guition_3_5/ex01_hello_bb_captouch/main_01_01.cpp> ; Basic verification of BB CapTouch
;build_src_filter = +<../src/guition_3_5/ex01_hello_bb_captouch/main_01_02.cpp> ; Rotation testing with touch || 90 & 270 not functional
;build_src_filter = +<../src/guition_3_5/ex01_hello_bb_captouch/main_01_03.cpp> ; Weird test that gemini spontanesouly generated


[env:guition_3_5_ex02_hello_lvgl]
extends = env:guition_3_5_base
lib_deps = 
    ${common.lib_deps}
    https://github.com/psyfiend/bb_spi_lcd.git  ;bitbank2/bb_spi_lcd
    lvgl/lvgl @ ^9.3.0
build_flags = 
    ${common.build_flags}
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_SKIP
    -D LV_USE_LOG=1
    -D LV_LOG_PRINTF=1
    -D LV_COLOR_DEPTH=16
    -D LV_COLOR_16_SWAP=0 
    -D LV_MEM_CUSTOM=1
    -D LV_TICK_CUSTOM=1
    ;-I include/gui
build_src_filter = +<../src/guition_3_5/ex02_hello_lvgl/main_02_01.cpp>

[env:WaveShare_S3_SMART86_ex00_hello_bb_spi]
extends = env:WaveShare_S3_SMART86_base
lib_deps = 
    ${common.lib_deps}
    https://github.com/psyfiend/Arduino_GFX.git  ;Arduino GFX library 
build_src_filter = +<../src/WS_S3_SMART86/ex00_hello_bb_spi/main_00_00.cpp> ; fillScreen() test
;build_src_filter = +<../src/WS_S3_SMART86/ex00_hello_bb_spi/main_00_01.cpp> ; Primitive tests: drawing, shapes, text, fills etc

[env:WaveShare_S3_SMART86_ex00_hello_ArduinoGFX]
extends = env:WaveShare_S3_SMART86_base
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags}
build_src_filter = +<../src/WS_S3_SMART86/ex000_Hello_Arduino_GFX/main_000_01.cpp> ; Basic Arduino GFX test