; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = guition_3_5_ex00_hello_bb_spi
extra_configs = platformio_override.ini

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

[common]
lib_deps = 
;    lvgl/lvgl @ ^9.3.0
    bitbank2/bb_spi_lcd
    bitbank2/bb_captouch
    https://github.com/bitbank2/bb_lvgl.git ; bitbank super LVGL glue library (only included so I can access the files quickly from vscode)

build_flags = 
    -D LV_LVGL_H_INCLUDE_SIMPLE
    ;-D LV_CONF_INCLUDE_SIMPLE
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_LOOP_STACK_SIZE=16384
    -mfix-esp32-psram-cache-issue

[env:guition_3_5_base]
board = esp32-s3-n16r8-Guition_JC3248W535EN
;board = esp32-s3-devkitc1-n16r8
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio

[env:waveshare_smart_86_box]
board = esp32s3box
lib_deps = ${common.lib_deps}
build_flags = ${common.build_flags}
build_src_filter = +<../src/waveshare_smart86/ex00_hello_bb_spi/*.cpp>  ; Gemini
;build_src_filter = +<../src/waveshare_smart86/ex01_hello_lvgl>  ;   Example 01 - Hello LVGL on Waveshare Box