[env:guition_3_5_ex02_hello_lvgl]
extends = env:guition_3_5_base
lib_deps = 
    ${env:guition_3_5_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/guition_3_5/_Common/LVGL_MultiTouch.cpp> ; Test multi-touch functionality with LVGL UI
        ;build_src_filter = +<../src/guition_3_5/ex02_hello_lvgl/LVGL_captouch_Fleet.cpp> ; LVGL Captouch test


[env:guition_3_5_ex03_hello_arduino_gfx]
extends = env:guition_3_5_base
build_src_filter = +<../src/guition_3_5/ex03_Hello_Arduino_GFX/HelloWorld_Fleet_BSP.cpp> ; Basic Hello World test with Fleet_BSP


[env:guition_8048w550_ex01_hello_arduino_gfx]
extends = env:guition_8048w550_base
lib_deps = ${env:guition_8048w550_base.lib_deps}
build_src_filter = +<../src/guition_8048/ex01_hello_arduino_gfx/ESPWiFiAnalyzer.cpp> ; ESP WiFi Analyzer test with Arduino_GFX_Library
        ;build_src_filter = +<../src/guition_8048/ex01_Hello_Arduino_GFX/HelloWorld_Fleet_BSP.cpp> ; Basic Hello World test with Fleet_BSP


[env:guition_8048w550_ex02_hello_lvgl]
extends = env:guition_8048w550_base
lib_deps = 
    ${env:guition_8048w550_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/guition_8048/ex02_Hello_LVGL/LVGL_captouch_Fleet.cpp> ; LVGL Captouch test with Fleet_BSP



[env:waveshare_s3_smart86_ex000_Hello_Arduino_GFX]
extends = env:waveshare_s3_smart86_base
lib_deps = ${env:waveshare_s3_smart86_base.lib_deps}
build_src_filter = +<../src/WS_S3_SMART86/ex000_Hello_Arduino_GFX/HelloWorld_Fleet_BSP.cpp> ; Basic Hello World test with Fleet_BSP

[env:waveshare_s3_smart86_ex01_hello_lvgl]
extends = env:waveshare_s3_smart86_base
lib_deps = 
    ${env:waveshare_s3_smart86_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_Hello_LVGL/03_LVGL_PCF85063_simpleTime.cpp> ; LVGL with PCF85063 RTC simple time display
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/04_LVGL_QMI8658_ui.cpp> ; LVGL with QMI8658 IMU based UI navigation
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/05_LVGL_AXP2101_ADC_Data.cpp> ; LVGL with AXP2101 power management ADC data display
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/AXP2101 Charge Monitor/*> ; AXP2101 power management charge monitor UI
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/gemini_LVGL_hello_world.cpp> ; Basic LVGL Hello World test
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/hello_display_init.cpp> ; Display init with LVGL log output
        ;build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/main_refactored_DisplayManager_test.cpp> ; Refactored DisplayManager test with LVGL
build_src_filter = +<../src/WS_S3_SMART86/ex01_hello_lvgl/LVGL_captouch.cpp> ; LVGL Captouch test

[env:waveshare_s3_smart86_ex02_advanced_hardware_testing]
extends = env:waveshare_s3_smart86_base
lib_deps = ${env:waveshare_s3_smart86_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/WS_S3_SMART86/ex02_Advanced_Hardware_Testing/LVGL_Audio_Test.cpp> ; Test audio functionality with LVGL UI


[env:waveshare_p4_smart86_ex00_getting_started]
extends = env:waveshare_p4_smart86_base
lib_deps = ${env:waveshare_p4_smart86_base.lib_deps}
build_src_filter = +<../src/WS_P4_SMART86/ex00_getting_started/HelloWorld.cpp> ; Basic Hello World test


[env:waveshare_p4_7b_ex00_getting_started]
extends = env:waveshare_p4_7b_base
lib_deps = 
    ${env:waveshare_p4_7b_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/WS_P4_7B/ex00_getting_started/LVGL_Brightness_Touch_Test.cpp> ; LVGL Brightness Touch test
        ;build_src_filter = +<../src/WS_P4_7B/ex00_getting_started/LVGL_captouch_Fleet.cpp> ; LVGL Captouch test
        ;build_src_filter = +<../src/WS_P4_7B/ex00_getting_started/HelloWorld_Fleet.cpp> ; Basic Hello World test

[env:waveshare_p4_7b_ex01_Advanced_Hardware_Testing]
extends = env:waveshare_p4_7b_base
lib_deps = 
    ${env:waveshare_p4_7b_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl    
        ;build_src_filter = +<../src/_Common/LVGL_Test_UI.cpp> ; Common LVGL Test UI elements
        ;build_src_filter = +<../src/WS_P4_7B/ex01_Advanced_Hardware_Testing/LVGL_Audio_Test.cpp> ; Test audio functionality with LVGL UI    
        ;build_src_filter = +<../src/WS_P4_7B/ex01_Advanced_Hardware_Testing/LVGL_MultiTouch.cpp> ; Test multi-touch functionality with LVGL UI
        ;build_src_filter = +<../src/_Common/i2c_scanner.cpp> ; I2C Scanner utility



[env:guition_1060p470_ex00_getting_started]
extends = env:guition_1060p470c_base
lib_deps = 
    ${env:guition_1060p470c_base.lib_deps}
    lvgl=symlink://c:/Users/Marge/Documents/PlatformIO/Projects/ESP32 Voice Assistant Fleet/VA Testing/components/lvgl
build_src_filter = +<../src/guition_1060p470/ex00_getting_started/LVGL_Brightness_Touch_Test.cpp> ; LVGL Brightness Touch test
        ;build_src_filter = +<../src/guition_1060p470/ex00_getting_started/LVGL_captouch_Fleet.cpp> ; LVGL Captouch test
        ;build_src_filter = +<../src/guition_1060p470/ex00_getting_started/HelloWorld_Fleet.cpp> ; Basic Hello World test
