"""
PlatformIO pre-build hook: derive FW_VERSION from git and inject it as a build flag.

Versioning scheme is A.B.C.D (see docs/ROADMAP.md section 3.3):

    A  major   breaking changes            \
    B  minor   new features, compatible     >  you set these by tagging: `git tag v0.1.0`
    C  patch   fixes, performance          /
    D  build   every commit                  <- AUTOMATIC, never typed by hand

D is the number of commits since the most recent tag, so it increments on its own and
cannot drift. You only ever tag A.B.C.

    tag v0.1.0, then 14 commits  ->  0.1.0.14
    uncommitted local changes    ->  0.1.0.14+dirty
    no tags in the repo yet      ->  0.0.0.<total commits>

The "+dirty" suffix matters when debugging a board on a wall: it makes a hand-modified
local build impossible to mistake for a real tagged release.

Wired up from platformio.ini via:  extra_scripts = pre:scripts/fw_version.py

WHY A GENERATED HEADER AND NOT A -D  (issue #46)
------------------------------------------------
This used to do env.Append(CPPDEFINES=...), which puts -D FW_VERSION on EVERY
translation unit in the build - all of LVGL, all of Arduino, every component -
when exactly three files use it. And the value changes constantly: D increments
on every commit, and "+dirty" appears and disappears as the tree is edited. Any
change to a compile flag invalidates that file in the content-addressed build
cache, so a one-character edit anywhere rebuilt the world.

That is why `pio run -t upload` seemed to recompile everything no matter what.

Now it writes a header and only rewrites it WHEN THE CONTENT CHANGES, so the
three files that include it rebuild when the version really moves and nothing
else ever does.
"""

import io
import os
import subprocess

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)


def _git(*args):
    """Run a git command in the project dir, return stripped stdout or None."""
    try:
        out = subprocess.check_output(
            ["git"] + list(args),
            cwd=env.subst("$PROJECT_DIR"),  # noqa: F821
            stderr=subprocess.DEVNULL,
        )
        return out.decode("utf-8", "replace").strip()
    except Exception:
        # No git, not a repo, git not on PATH - all non-fatal. Build must not break
        # just because version metadata is unavailable.
        return None


def _describe():
    """Return (version, commit) derived from git state."""
    commit = _git("rev-parse", "--short=8", "HEAD") or "unknown"

    # --long always includes the count+sha, even when HEAD is exactly on a tag,
    # which keeps parsing uniform instead of special-casing the on-tag form.
    desc = _git("describe", "--tags", "--long", "--match", "v[0-9]*")

    if desc:
        # e.g. "v0.1.0-14-gabc12345"
        base, count, _sha = desc.rsplit("-", 2)
        version = "{}.{}".format(base.lstrip("v"), count)
    else:
        # No matching tag yet. Fall back to total commit count so the number is
        # still monotonic and still tells you which build you're looking at.
        count = _git("rev-list", "--count", "HEAD") or "0"
        version = "0.0.0.{}".format(count)

    # Any tracked modification, staged or not, makes this not a reproducible build.
    if _git("status", "--porcelain", "--untracked-files=no"):
        version += "+dirty"

    return version, commit


version, commit = _describe()

# Written into include/, which is on the include path for project sources and
# for the local components alike. Generated, so it is gitignored - the pre:
# hook guarantees it exists before anything compiles.
_HEADER = os.path.join(env.subst("$PROJECT_INCLUDE_DIR"), "fleet_fw_version.h")  # noqa: F821

_body = """#pragma once
// GENERATED by scripts/fw_version.py - do not edit, do not commit.
//
// Derived from `git describe`. See docs/ROADMAP.md section 3.3 for the scheme.
#define FW_VERSION "{v}"
#define FW_COMMIT  "{c}"
""".format(v=version, c=commit)

# ONLY REWRITE ON A REAL CHANGE. Touching this file unconditionally would put
# every build back to rebuilding its three dependents, and - worse - would make
# the tree look modified, which is what "+dirty" keys off.
_old = None
try:
    with io.open(_HEADER, encoding="utf-8") as f:
        _old = f.read()
except Exception:
    pass

if _old != _body:
    try:
        os.makedirs(os.path.dirname(_HEADER), exist_ok=True)
        with io.open(_HEADER, "w", encoding="utf-8", newline=chr(10)) as f:
            f.write(_body)
        print("fw_version: wrote {}".format(os.path.basename(_HEADER)))
    except Exception as exc:
        # Non-fatal, exactly like a missing git. The consumers all carry an
        # #ifndef fallback, so the build still succeeds with "unknown".
        print("fw_version: could not write header ({})".format(exc))

print("fw_version: FW_VERSION={} FW_COMMIT={}".format(version, commit))
