#pragma once
#ifndef CARD_ICONS_H
#define CARD_ICONS_H

#include <stdint.h>
#include "Entity.h"
#include "Cards/CardTypes.h"   // TempUnit
#include <lvgl.h>              // lv_font_t, for cardGlyphTopBearing()

// ---------------------------------------------------------------------------
// Icons and tints, by what an entity MEASURES rather than by card type.
//
// These are REAL MATERIAL DESIGN ICONS now, not the LVGL built-in stand-ins
// that stood here through most of milestone 2.4. The subset is generated by
// scripts/gen_icon_font.py into include/UI/UIIcons.h - 84 glyphs at two sizes
// per board, derived from real pixel density like everything else.
//
// Resolution order, and the first step is the one cards.md section 5 actually
// asked for:
//
//   1. the entity's OWN icon      "mdi:thermometer" straight off the descriptor
//   2. its device_class           temperature, occupancy, battery...
//   3. its domain                 a light, a switch, a button
//
// Step 1 was impossible until the subset existed, so every descriptor's icon
// field was being ignored. An unknown name falls through rather than drawing
// an approximation, because a confidently wrong icon is worse than a generic
// one - the same reasoning behind everything else in this project that
// refuses to guess.
//
// The TINTS are unrelated and were never placeholders. UIPalette's sensor
// tints are design tokens with a job - cards.md section 0: a wall of sensor
// cards should be scannable by colour before you read a single number.
// ---------------------------------------------------------------------------

// The glyph for this entity. Never null.
const char *cardIconFor(const EntityDescriptor &d);

// The icon's tint, as a 0xRRGGBB from the ACTIVE palette. Call it at render
// time and never cache the result - the active palette is a mutable copy that
// UI::setScheme() edits live.
uint32_t cardTintFor(const EntityDescriptor &d);

// The glyph for an entity in a given state, where the two read differently
// enough to be worth it - motion present or absent, a door open or shut. Falls
// back to cardIconFor() when a state pair would be two near-identical glyphs,
// because the card already carries state in its colour.
const char *cardIconForState(const EntityDescriptor &d, bool on);

// The battery glyph for a percentage, in six steps.
const char *cardBatteryGlyph(int pct);

// A stable colour for an area name. The same name always gives the same
// colour, on every board and across reboots, because it is derived from the
// string rather than handed out in arrival order - two panels showing the same
// house must agree about what "Kitchen" looks like. Returns 0 for an empty
// name, meaning "no area, use the accent".
uint32_t cardAreaColor(const char *area);

// Compact age, written into `out`: "now", "45s", "12m", "3h", "2d".
//
// ASCII only, no exceptions and no cleverness. CLAUDE.md: LVGL's stock
// Montserrat covers ASCII plus a small symbol set, and the middle dot and em
// dash that a designer would reach for here render as empty boxes on the
// panels. The degree sign is the one non-ASCII character in range, and it
// arrives from the entity's unit string rather than from here.
void cardFormatAge(uint32_t ageMs, char *out, size_t cap);

// The entity's value as text, with its unit appended when it has one.
// Booleans deliberately produce no words - cards.md section 4 forbids
// "On"/"Off"/"Open"/"Closed" text anywhere, because state is the icon and its
// colour. A bool renders as an empty string here and the card draws the icon.
// ---------------------------------------------------------------------------
// Units.
//
// The owner, 2026-09-15: "I will always prefer temp in F not C but both should
// be supported and customizable by users if the source is not in the unit they
// want." So the fleet has a preference, a page may override it and a card may
// override that, and anything already in the wanted unit is left alone.
//
// CONVERSION IS A DISPLAY CONCERN AND HAPPENS HERE, at format time. The
// registry keeps whatever the source actually said, because that value is what
// an echo is compared against, what an optimistic write reverts to, and what
// our own HA discovery would publish - converting on the way in would corrupt
// all three and the damage would be invisible.
//
// Confirmed against the owner's real Home Assistant: 34 of 35 temperature
// sensors report Fahrenheit and one reports Celsius. A fleet with a preference
// and no conversion renders that one card wrong, silently, and it looks
// exactly like a working card.
// How much EMPTY SPACE sits between the top of a label's line box and the top
// of the glyph's actual ink, for this font and this glyph, in pixels.
//
// Why this exists. A label's box is a LINE box: it is as tall as the font's
// line height, and a glyph does not fill it - there is leading above the ink
// and a descender gap below. So aligning an icon label TOP_LEFT puts its BOX
// in the corner, and the thing you can see sits noticeably lower.
//
// The owner has tried to correct this by eye twice and both attempts made
// something else worse, because a hand-picked nudge is right for one font size
// and one header mode and wrong for the rest. This measures it instead:
// baseline is at (line_height - base_line) from the top of the box, and the
// glyph's ink reaches (ofs_y + box_h) above the baseline.
//
// Returns 0 if the glyph is not in the font, which is the safe answer.
int32_t cardGlyphTopBearing(const lv_font_t *font, const char *utf8);

void     cardSetTempUnit(TempUnit u);     // the fleet default
TempUnit cardTempUnit();

// The unit string to DISPLAY for this entity, which is not always desc.unit.
// Returns "" when the entity has no unit at all.
const char *cardDisplayUnit(const Entity &e, TempUnit want = TempUnit::TEMP_INHERIT);

void cardFormatValue(const Entity &e, char *out, size_t cap, bool withUnit = true,
                     TempUnit want = TempUnit::TEMP_INHERIT);

#endif // CARD_ICONS_H
