#pragma once
#ifndef CARD_ICONS_H
#define CARD_ICONS_H

#include <stdint.h>
#include "Entity.h"

// ---------------------------------------------------------------------------
// Icons and tints, by what an entity MEASURES rather than by card type.
//
// These are REAL MATERIAL DESIGN ICONS now, not the LVGL built-in stand-ins
// that stood here through most of milestone 2.4. The subset is generated by
// scripts/gen_icon_font.py into include/UI/UIIcons.h - 84 glyphs at two sizes
// per board, derived from real pixel density like everything else.
//
// Resolution order, and the first step is the one cards.md section 5 actually
// asked for:
//
//   1. the entity's OWN icon      "mdi:thermometer" straight off the descriptor
//   2. its device_class           temperature, occupancy, battery...
//   3. its domain                 a light, a switch, a button
//
// Step 1 was impossible until the subset existed, so every descriptor's icon
// field was being ignored. An unknown name falls through rather than drawing
// an approximation, because a confidently wrong icon is worse than a generic
// one - the same reasoning behind everything else in this project that
// refuses to guess.
//
// The TINTS are unrelated and were never placeholders. UIPalette's sensor
// tints are design tokens with a job - cards.md section 0: a wall of sensor
// cards should be scannable by colour before you read a single number.
// ---------------------------------------------------------------------------

// The glyph for this entity. Never null.
const char *cardIconFor(const EntityDescriptor &d);

// The icon's tint, as a 0xRRGGBB from the ACTIVE palette. Call it at render
// time and never cache the result - the active palette is a mutable copy that
// UI::setScheme() edits live.
uint32_t cardTintFor(const EntityDescriptor &d);

// The glyph for an entity in a given state, where the two read differently
// enough to be worth it - motion present or absent, a door open or shut. Falls
// back to cardIconFor() when a state pair would be two near-identical glyphs,
// because the card already carries state in its colour.
const char *cardIconForState(const EntityDescriptor &d, bool on);

// The battery glyph for a percentage, in six steps.
const char *cardBatteryGlyph(int pct);

// Compact age, written into `out`: "now", "45s", "12m", "3h", "2d".
//
// ASCII only, no exceptions and no cleverness. CLAUDE.md: LVGL's stock
// Montserrat covers ASCII plus a small symbol set, and the middle dot and em
// dash that a designer would reach for here render as empty boxes on the
// panels. The degree sign is the one non-ASCII character in range, and it
// arrives from the entity's unit string rather than from here.
void cardFormatAge(uint32_t ageMs, char *out, size_t cap);

// The entity's value as text, with its unit appended when it has one.
// Booleans deliberately produce no words - cards.md section 4 forbids
// "On"/"Off"/"Open"/"Closed" text anywhere, because state is the icon and its
// colour. A bool renders as an empty string here and the card draws the icon.
void cardFormatValue(const Entity &e, char *out, size_t cap, bool withUnit = true);

#endif // CARD_ICONS_H
