#pragma once
#ifndef UI_ICONS_H
#define UI_ICONS_H

// GENERATED by scripts/gen_icon_font.py - do not edit by hand.
//
// The fleet's Material Design Icons subset: 89 glyphs, at three sizes
// derived per board from real pixel density. MDI is Apache 2.0; see
// assets/fonts/materialdesignicons-LICENSE.txt, vendored beside the font.
//
// Glyphs are UTF-8 string literals so they can be handed straight to
// lv_label_set_text(). The name of each constant is the Home Assistant
// icon name, which is what an EntityDescriptor already carries.

#include <lvgl.h>
#include "bsp_loader.h"

LV_FONT_DECLARE(fleet_icons_18);
LV_FONT_DECLARE(fleet_icons_20);
LV_FONT_DECLARE(fleet_icons_24);
LV_FONT_DECLARE(fleet_icons_26);
LV_FONT_DECLARE(fleet_icons_28);
LV_FONT_DECLARE(fleet_icons_30);
LV_FONT_DECLARE(fleet_icons_32);
LV_FONT_DECLARE(fleet_icons_34);
LV_FONT_DECLARE(fleet_icons_36);
LV_FONT_DECLARE(fleet_icons_42);
LV_FONT_DECLARE(fleet_icons_46);
LV_FONT_DECLARE(fleet_icons_52);

#if defined(CYD_P4_1060)
    #define FLEET_ICONS_LG (&fleet_icons_30)
    #define FLEET_ICONS_MD (&fleet_icons_24)
    #define FLEET_ICONS_SM (&fleet_icons_18)
#elif defined(CYD_S3_3248)
    #define FLEET_ICONS_LG (&fleet_icons_30)
    #define FLEET_ICONS_MD (&fleet_icons_24)
    #define FLEET_ICONS_SM (&fleet_icons_18)
#elif defined(CYD_S3_8048)
    #define FLEET_ICONS_LG (&fleet_icons_34)
    #define FLEET_ICONS_MD (&fleet_icons_26)
    #define FLEET_ICONS_SM (&fleet_icons_20)
#elif defined(WS_P4_4B)
    #define FLEET_ICONS_LG (&fleet_icons_46)
    #define FLEET_ICONS_MD (&fleet_icons_36)
    #define FLEET_ICONS_SM (&fleet_icons_28)
#elif defined(WS_P4_5)
    #define FLEET_ICONS_LG (&fleet_icons_52)
    #define FLEET_ICONS_MD (&fleet_icons_42)
    #define FLEET_ICONS_SM (&fleet_icons_32)
#elif defined(WS_P4_7B)
    #define FLEET_ICONS_LG (&fleet_icons_30)
    #define FLEET_ICONS_MD (&fleet_icons_24)
    #define FLEET_ICONS_SM (&fleet_icons_18)
#elif defined(WS_S3_4B)
    #define FLEET_ICONS_LG (&fleet_icons_30)
    #define FLEET_ICONS_MD (&fleet_icons_24)
    #define FLEET_ICONS_SM (&fleet_icons_18)
#elif defined(WS_S3_5B)
    #define FLEET_ICONS_LG (&fleet_icons_42)
    #define FLEET_ICONS_MD (&fleet_icons_34)
    #define FLEET_ICONS_SM (&fleet_icons_26)
#else
    #error "No icon font for this board - rerun scripts/gen_icon_font.py"
#endif

// --- the glyphs -------------------------------------------------------
// Sorted by name. MDI codepoints live in the private use area, so these
// are meaningless to any other font - which is why CardIcons.cpp must
// always resolve through this table rather than passing a name through.

#define MDI_ACCOUNT                    "\xF3\xB0\x80\x84"   // U+F0004
#define MDI_ACCOUNT_OFF                "\xF3\xB0\x80\x92"   // U+F0012
#define MDI_AIR_FILTER                 "\xF3\xB0\xB5\x83"   // U+F0D43
#define MDI_ALERT                      "\xF3\xB0\x80\xA6"   // U+F0026
#define MDI_ALERT_CIRCLE               "\xF3\xB0\x80\xA8"   // U+F0028
#define MDI_BATTERY                    "\xF3\xB0\x81\xB9"   // U+F0079
#define MDI_BATTERY_10                 "\xF3\xB0\x81\xBA"   // U+F007A
#define MDI_BATTERY_30                 "\xF3\xB0\x81\xBC"   // U+F007C
#define MDI_BATTERY_50                 "\xF3\xB0\x81\xBE"   // U+F007E
#define MDI_BATTERY_70                 "\xF3\xB0\x82\x80"   // U+F0080
#define MDI_BATTERY_90                 "\xF3\xB0\x82\x82"   // U+F0082
#define MDI_BATTERY_ALERT              "\xF3\xB0\x82\x83"   // U+F0083
#define MDI_BATTERY_CHARGING           "\xF3\xB0\x82\x84"   // U+F0084
#define MDI_BATTERY_OUTLINE            "\xF3\xB0\x82\x8E"   // U+F008E
#define MDI_BRIGHTNESS_5               "\xF3\xB0\x83\x9E"   // U+F00DE
#define MDI_CEILING_LIGHT              "\xF3\xB0\x9D\xA9"   // U+F0769
#define MDI_CEILING_LIGHT_OUTLINE      "\xF3\xB1\x9F\x87"   // U+F17C7
#define MDI_CHECK_CIRCLE               "\xF3\xB0\x97\xA0"   // U+F05E0
#define MDI_CHEVRON_RIGHT              "\xF3\xB0\x85\x82"   // U+F0142
#define MDI_CLOCK_OUTLINE              "\xF3\xB0\x85\x90"   // U+F0150
#define MDI_CLOSE_CIRCLE               "\xF3\xB0\x85\x99"   // U+F0159
#define MDI_COACH_LAMP                 "\xF3\xB1\x80\xA0"   // U+F1020
#define MDI_DOOR_CLOSED                "\xF3\xB0\xA0\x9B"   // U+F081B
#define MDI_DOOR_OPEN                  "\xF3\xB0\xA0\x9C"   // U+F081C
#define MDI_DOTS_HORIZONTAL            "\xF3\xB0\x87\x98"   // U+F01D8
#define MDI_FAN                        "\xF3\xB0\x88\x90"   // U+F0210
#define MDI_FAN_OFF                    "\xF3\xB0\xA0\x9D"   // U+F081D
#define MDI_FIRE                       "\xF3\xB0\x88\xB8"   // U+F0238
#define MDI_FLASH                      "\xF3\xB0\x89\x81"   // U+F0241
#define MDI_GARAGE                     "\xF3\xB0\x9B\x99"   // U+F06D9
#define MDI_GARAGE_OPEN                "\xF3\xB0\x9B\x9A"   // U+F06DA
#define MDI_GAUGE                      "\xF3\xB0\x8A\x9A"   // U+F029A
#define MDI_GESTURE_TAP_BUTTON         "\xF3\xB1\x8A\xA8"   // U+F12A8
#define MDI_HELP_CIRCLE                "\xF3\xB0\x8B\x97"   // U+F02D7
#define MDI_HOME_AUTOMATION            "\xF3\xB0\x9F\x91"   // U+F07D1
#define MDI_IP_NETWORK                 "\xF3\xB0\xA9\xA0"   // U+F0A60
#define MDI_LAMP                       "\xF3\xB0\x9A\xB5"   // U+F06B5
#define MDI_LAN_DISCONNECT             "\xF3\xB0\x8C\x99"   // U+F0319
#define MDI_LED_STRIP_VARIANT          "\xF3\xB1\x81\x91"   // U+F1051
#define MDI_LIGHT_RECESSED             "\xF3\xB1\x9E\x9B"   // U+F179B
#define MDI_LIGHTBULB                  "\xF3\xB0\x8C\xB5"   // U+F0335
#define MDI_LIGHTBULB_GROUP            "\xF3\xB1\x89\x93"   // U+F1253
#define MDI_LIGHTBULB_GROUP_OUTLINE    "\xF3\xB1\x89\x94"   // U+F1254
#define MDI_LIGHTBULB_OUTLINE          "\xF3\xB0\x8C\xB6"   // U+F0336
#define MDI_LIGHTNING_BOLT             "\xF3\xB1\x90\x8B"   // U+F140B
#define MDI_LOCK                       "\xF3\xB0\x8C\xBE"   // U+F033E
#define MDI_LOCK_OPEN_VARIANT          "\xF3\xB0\xBF\x86"   // U+F0FC6
#define MDI_MEMORY                     "\xF3\xB0\x8D\x9B"   // U+F035B
#define MDI_MOLECULE_CO2               "\xF3\xB0\x9F\xA4"   // U+F07E4
#define MDI_MOTION_SENSOR              "\xF3\xB0\xB6\x91"   // U+F0D91
#define MDI_MOTION_SENSOR_OFF          "\xF3\xB1\x90\xB5"   // U+F1435
#define MDI_MOVIE_OPEN                 "\xF3\xB0\xBF\x8E"   // U+F0FCE
#define MDI_PALETTE                    "\xF3\xB0\x8F\x98"   // U+F03D8
#define MDI_PAUSE_CIRCLE               "\xF3\xB0\x8F\xA5"   // U+F03E5
#define MDI_PLAY_CIRCLE                "\xF3\xB0\x90\x8C"   // U+F040C
#define MDI_POWER                      "\xF3\xB0\x90\xA5"   // U+F0425
#define MDI_POWER_PLUG                 "\xF3\xB0\x9A\xA5"   // U+F06A5
#define MDI_POWER_PLUG_OFF             "\xF3\xB0\x9A\xA6"   // U+F06A6
#define MDI_SCRIPT_TEXT                "\xF3\xB0\xAF\x82"   // U+F0BC2
#define MDI_SHIELD_ALERT               "\xF3\xB0\xBB\x8C"   // U+F0ECC
#define MDI_SHIELD_CHECK               "\xF3\xB0\x95\xA5"   // U+F0565
#define MDI_SMOKE_DETECTOR             "\xF3\xB0\x8E\x92"   // U+F0392
#define MDI_SNOWFLAKE                  "\xF3\xB0\x9C\x97"   // U+F0717
#define MDI_SPEEDOMETER                "\xF3\xB0\x93\x85"   // U+F04C5
#define MDI_SUN_THERMOMETER            "\xF3\xB1\xA3\x96"   // U+F18D6
#define MDI_SYNC                       "\xF3\xB0\x93\xA6"   // U+F04E6
#define MDI_SYNC_ALERT                 "\xF3\xB0\x93\xA7"   // U+F04E7
#define MDI_THERMOMETER                "\xF3\xB0\x94\x8F"   // U+F050F
#define MDI_THERMOMETER_HIGH           "\xF3\xB1\x83\x82"   // U+F10C2
#define MDI_THERMOMETER_LOW            "\xF3\xB1\x83\x83"   // U+F10C3
#define MDI_THERMOSTAT                 "\xF3\xB0\x8E\x93"   // U+F0393
#define MDI_TOGGLE_SWITCH              "\xF3\xB0\x94\xA1"   // U+F0521
#define MDI_TOGGLE_SWITCH_OFF          "\xF3\xB0\x94\xA2"   // U+F0522
#define MDI_VOLUME_HIGH                "\xF3\xB0\x95\xBE"   // U+F057E
#define MDI_WATER_ALERT                "\xF3\xB1\x94\x82"   // U+F1502
#define MDI_WATER_PERCENT              "\xF3\xB0\x96\x8E"   // U+F058E
#define MDI_WEATHER_CLOUDY             "\xF3\xB0\x96\x90"   // U+F0590
#define MDI_WEATHER_FOG                "\xF3\xB0\x96\x91"   // U+F0591
#define MDI_WEATHER_NIGHT              "\xF3\xB0\x96\x94"   // U+F0594
#define MDI_WEATHER_PARTLY_CLOUDY      "\xF3\xB0\x96\x95"   // U+F0595
#define MDI_WEATHER_POURING            "\xF3\xB0\x96\x96"   // U+F0596
#define MDI_WEATHER_RAINY              "\xF3\xB0\x96\x97"   // U+F0597
#define MDI_WEATHER_SNOWY              "\xF3\xB0\x96\x98"   // U+F0598
#define MDI_WEATHER_SUNNY              "\xF3\xB0\x96\x99"   // U+F0599
#define MDI_WEATHER_WINDY              "\xF3\xB0\x96\x9D"   // U+F059D
#define MDI_WIFI                       "\xF3\xB0\x96\xA9"   // U+F05A9
#define MDI_WIFI_OFF                   "\xF3\xB0\x96\xAA"   // U+F05AA
#define MDI_WINDOW_CLOSED              "\xF3\xB0\x96\xAE"   // U+F05AE
#define MDI_WINDOW_OPEN                "\xF3\xB0\x96\xB1"   // U+F05B1

// --- name lookup ------------------------------------------------------
//
// cards.md section 5: "Prefer provider-supplied. We already publish an
// `icon` in our own MQTT discovery payloads, so the inbound direction
// should be symmetrical." Every EntityDescriptor already carries one, so
// this is what turns that string into something drawable.
//
// A linear scan over 89 entries, run once per card per repaint. Sorting
// and bisecting would be faster and is not worth the generated code - a
// repaint already costs orders of magnitude more than this.
struct MdiEntry { const char *name; const char *glyph; };

inline const MdiEntry MDI_TABLE[] = {
    { "account", MDI_ACCOUNT },
    { "account-off", MDI_ACCOUNT_OFF },
    { "air-filter", MDI_AIR_FILTER },
    { "alert", MDI_ALERT },
    { "alert-circle", MDI_ALERT_CIRCLE },
    { "battery", MDI_BATTERY },
    { "battery-10", MDI_BATTERY_10 },
    { "battery-30", MDI_BATTERY_30 },
    { "battery-50", MDI_BATTERY_50 },
    { "battery-70", MDI_BATTERY_70 },
    { "battery-90", MDI_BATTERY_90 },
    { "battery-alert", MDI_BATTERY_ALERT },
    { "battery-charging", MDI_BATTERY_CHARGING },
    { "battery-outline", MDI_BATTERY_OUTLINE },
    { "brightness-5", MDI_BRIGHTNESS_5 },
    { "ceiling-light", MDI_CEILING_LIGHT },
    { "ceiling-light-outline", MDI_CEILING_LIGHT_OUTLINE },
    { "check-circle", MDI_CHECK_CIRCLE },
    { "chevron-right", MDI_CHEVRON_RIGHT },
    { "clock-outline", MDI_CLOCK_OUTLINE },
    { "close-circle", MDI_CLOSE_CIRCLE },
    { "coach-lamp", MDI_COACH_LAMP },
    { "door-closed", MDI_DOOR_CLOSED },
    { "door-open", MDI_DOOR_OPEN },
    { "dots-horizontal", MDI_DOTS_HORIZONTAL },
    { "fan", MDI_FAN },
    { "fan-off", MDI_FAN_OFF },
    { "fire", MDI_FIRE },
    { "flash", MDI_FLASH },
    { "garage", MDI_GARAGE },
    { "garage-open", MDI_GARAGE_OPEN },
    { "gauge", MDI_GAUGE },
    { "gesture-tap-button", MDI_GESTURE_TAP_BUTTON },
    { "help-circle", MDI_HELP_CIRCLE },
    { "home-automation", MDI_HOME_AUTOMATION },
    { "ip-network", MDI_IP_NETWORK },
    { "lamp", MDI_LAMP },
    { "lan-disconnect", MDI_LAN_DISCONNECT },
    { "led-strip-variant", MDI_LED_STRIP_VARIANT },
    { "light-recessed", MDI_LIGHT_RECESSED },
    { "lightbulb", MDI_LIGHTBULB },
    { "lightbulb-group", MDI_LIGHTBULB_GROUP },
    { "lightbulb-group-outline", MDI_LIGHTBULB_GROUP_OUTLINE },
    { "lightbulb-outline", MDI_LIGHTBULB_OUTLINE },
    { "lightning-bolt", MDI_LIGHTNING_BOLT },
    { "lock", MDI_LOCK },
    { "lock-open-variant", MDI_LOCK_OPEN_VARIANT },
    { "memory", MDI_MEMORY },
    { "molecule-co2", MDI_MOLECULE_CO2 },
    { "motion-sensor", MDI_MOTION_SENSOR },
    { "motion-sensor-off", MDI_MOTION_SENSOR_OFF },
    { "movie-open", MDI_MOVIE_OPEN },
    { "palette", MDI_PALETTE },
    { "pause-circle", MDI_PAUSE_CIRCLE },
    { "play-circle", MDI_PLAY_CIRCLE },
    { "power", MDI_POWER },
    { "power-plug", MDI_POWER_PLUG },
    { "power-plug-off", MDI_POWER_PLUG_OFF },
    { "script-text", MDI_SCRIPT_TEXT },
    { "shield-alert", MDI_SHIELD_ALERT },
    { "shield-check", MDI_SHIELD_CHECK },
    { "smoke-detector", MDI_SMOKE_DETECTOR },
    { "snowflake", MDI_SNOWFLAKE },
    { "speedometer", MDI_SPEEDOMETER },
    { "sun-thermometer", MDI_SUN_THERMOMETER },
    { "sync", MDI_SYNC },
    { "sync-alert", MDI_SYNC_ALERT },
    { "thermometer", MDI_THERMOMETER },
    { "thermometer-high", MDI_THERMOMETER_HIGH },
    { "thermometer-low", MDI_THERMOMETER_LOW },
    { "thermostat", MDI_THERMOSTAT },
    { "toggle-switch", MDI_TOGGLE_SWITCH },
    { "toggle-switch-off", MDI_TOGGLE_SWITCH_OFF },
    { "volume-high", MDI_VOLUME_HIGH },
    { "water-alert", MDI_WATER_ALERT },
    { "water-percent", MDI_WATER_PERCENT },
    { "weather-cloudy", MDI_WEATHER_CLOUDY },
    { "weather-fog", MDI_WEATHER_FOG },
    { "weather-night", MDI_WEATHER_NIGHT },
    { "weather-partly-cloudy", MDI_WEATHER_PARTLY_CLOUDY },
    { "weather-pouring", MDI_WEATHER_POURING },
    { "weather-rainy", MDI_WEATHER_RAINY },
    { "weather-snowy", MDI_WEATHER_SNOWY },
    { "weather-sunny", MDI_WEATHER_SUNNY },
    { "weather-windy", MDI_WEATHER_WINDY },
    { "wifi", MDI_WIFI },
    { "wifi-off", MDI_WIFI_OFF },
    { "window-closed", MDI_WINDOW_CLOSED },
    { "window-open", MDI_WINDOW_OPEN },
};
inline constexpr unsigned MDI_TABLE_N = sizeof(MDI_TABLE) / sizeof(MDI_TABLE[0]);

// Accepts either "mdi:thermometer" or plain "thermometer". Returns
// nullptr when the name is unknown, so a caller can fall through to its
// device_class mapping rather than drawing a wrong glyph confidently.
inline const char *mdiGlyph(const char *name) {
    if (!name || !name[0]) return nullptr;
    if (name[0] == 'm' && name[1] == 'd' && name[2] == 'i' && name[3] == ':') name += 4;
    for (unsigned i = 0; i < MDI_TABLE_N; i++) {
        const char *a = MDI_TABLE[i].name, *b = name;
        while (*a && *a == *b) { a++; b++; }
        if (!*a && !*b) return MDI_TABLE[i].glyph;
    }
    return nullptr;
}

#endif // UI_ICONS_H
