#pragma once
#ifndef UI_TYPE_SCALE_H
#define UI_TYPE_SCALE_H

// GENERATED by scripts/gen_type_scale.py - do not edit by hand.
//
// Each board's four faces, sized from ITS OWN pixel density so that text
// is the same physical size on every panel in the fleet. Targets, in mm
// on glass: TAG 1.90, UNIT 2.47, NAME 2.66, VALUE 5.89, ICON 4.50.
//
// Resolved with #if rather than at runtime on purpose: LVGL links every
// font a translation unit REFERENCES, at roughly 96 KB for a full ASCII
// face, so choosing at runtime would make every board carry the whole
// fleet's type scale to use a quarter of it.

#include <lvgl.h>
#include "bsp_loader.h"

LV_FONT_DECLARE(fleet_font_num_56);
LV_FONT_DECLARE(fleet_font_num_60);

#if defined(CYD_P4_1060)
    // CYD_P4_1060 - 170 PPI, 7.0"
    #define FLEET_FONT_VALUE  (&lv_font_montserrat_40)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_18)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_18)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_14)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_30)
#elif defined(CYD_S3_3248)
    // CYD_S3_3248 - 165 PPI, 3.5"
    #define FLEET_FONT_VALUE  (&lv_font_montserrat_38)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_18)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_16)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_12)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_30)
#elif defined(CYD_S3_8048)
    // CYD_S3_8048 - 187 PPI, 5.0"
    #define FLEET_FONT_VALUE  (&lv_font_montserrat_44)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_20)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_18)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_14)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_34)
#elif defined(WS_P4_4B)
    // WS_P4_4B - 255 PPI, 4.0"
    #define FLEET_FONT_VALUE  (&fleet_font_num_60)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_28)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_26)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_20)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_46)
#elif defined(WS_P4_5)
    // WS_P4_5 - 294 PPI, 5.0"
    #define FLEET_FONT_VALUE  (&fleet_font_num_60)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_28)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_26)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_20)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_46)
#elif defined(WS_P4_7B)
    // WS_P4_7B - 170 PPI, 7.0"
    #define FLEET_FONT_VALUE  (&lv_font_montserrat_40)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_18)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_18)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_14)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_30)
#elif defined(WS_S3_4B)
    // WS_S3_4B - 170 PPI, 4.0"
    #define FLEET_FONT_VALUE  (&lv_font_montserrat_40)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_18)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_18)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_14)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_30)
#elif defined(WS_S3_5B)
    // WS_S3_5B - 237 PPI, 5.0"
    #define FLEET_FONT_VALUE  (&fleet_font_num_56)
    #define FLEET_FONT_NAME   (&lv_font_montserrat_26)
    #define FLEET_FONT_UNIT   (&lv_font_montserrat_24)
    #define FLEET_FONT_TAG    (&lv_font_montserrat_18)
    #define FLEET_FONT_ICON   (&lv_font_montserrat_42)
#else
    #error "No type scale for this board - rerun scripts/gen_type_scale.py"
#endif

#endif // UI_TYPE_SCALE_H
